name: Build Svelte
on: 
  push:
    branches:
      - main
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Svelte
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'opt'
    - id: build-svelte
      uses: stilosdesign/svelte-pages-action@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        username: 'antonielbordin'
        reposname: 'testepage'
        repospage: 'gh-pages'        
        script: 'npm install && npm run build'
        buildfolder: 'dist'