name: Build Svelte
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Svelte
    steps:
    - uses: actions/checkout@v2
    - id: build-svelte
      uses: stilosdesign/svelte-page-action@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        username: 'antonielbordin'
        reposname: 'testepage'
        repospage: 'gh-pages'        
        scripts: 'npm install && npm run build'
        buildfolder: 'dist'